" Vim config

set nocompatible
filetype off
let mapleader=","                           " set mapleader to comma
set nomodeline                              " hide mode

" reload .vimrc
noremap <silent> <F5> :source ~/.vimrc

" do a word count
noremap <silent> <F7> g<C-G>

" Load plugins using vim-plug
" https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')

" For CSS
Plug 'ap/vim-css-color'

" For R integration
Plug 'jalvesaq/Nvim-R'
Plug 'gaalcaras/ncm-R'

" Code commenting
Plug 'tpope/vim-commentary'

" For Git
"Plug 'airblade/vim-gitgutter'

" For writing
" Center writing screen
Plug 'junegunn/goyo.vim'        
" Highlights line
Plug 'junegunn/limelight.vim'   
Plug 'reedes/vim-pencil'
Plug 'reedes/vim-wordy'
Plug 'godlygeek/tabular'
Plug 'Ron89/thesaurus_query.vim' 
" Zotero integration
Plug 'jalvesaq/zotcite'         

" Initialize plugin system
call plug#end()

" For vim-gitgutter
"set updatetime=100

" UI
syntax on
set background=dark " set to dark for most other colorschemes
set path+=**
set wildmenu
set wildmode=list:longest,full
set backspace=indent,eol,start
set ignorecase
set smartcase
set hlsearch
" remove highlights with spacebar
:noremap <silent> <Space> :silent noh<Bar>echo<CR>
set incsearch
set lazyredraw
set magic
set showmatch                               " highlight matching [{()}]
set noerrorbells visualbell t_vb=           " Disable annoying error noises
set number                                  " set line numbers
set shortmess+=I                            " disable startup message
set splitbelow                              " open new vertical splits bottom
set splitright                              " open new horizontal splits right
set textwidth=79
set autoindent
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2 softtabstop=2
set nojoinspaces
set showcmd                                 " show command in bottom bar
"set relativenumber                         " set relative numbering
"set scrolloff=12                           " Keep cursor near middle of screen
"set cursorline                             " highlight cursor line
let g:limelight_conceal_ctermfg = 'gray'    " to fix colorscheme
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!
autocmd! User GoyoEnter set nocursorline    " disable cursorline in Goyo
let g:goyo_width = 60

" Text 
set encoding=utf-8                          " set encoding to utf-8
set nospell                                 " disable automatic spellcheck 
setlocal spelllang=en_us                    " set spellcheck language
set spellfile=~/.vim/spellfile.add          " add custom spellings here
set thesaurus+=/home/sean/.vim/thesaurii.txt " local thesaurus

" File management
set backup
set backupdir=~/.backup
set directory=~/.backup

" Tabbed Vim
noremap <leader>tt :tabnew<cr>
noremap <leader>tc :tabclose<cr>
noremap <leader>tm :tabmove
noremap <leader>tn :tabnext<cr>
noremap <leader>tp :tabprevious<cr>

" Split vertical if horizontal
noremap <C-l> <C-W>L
" Split horizontal if vertical
noremap <C-j> <C-W>J
" Rotate splits
noremap <C-t> <C-w><C-r>

" Move to other pane
nnoremap <C-d> <C-W>w

" Omnicompletion (e.g., ZotCite)
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" ZotCite
let $ZCitationTemplate = '{author}{year}'

" R integration
let Rnvimpager="vertical"
let R_editor_w=80
let R_objbr_place = "RIGHT"

" For Pencil Plugin
let g:pencil#wrapModeDefault = 'soft'   " default is 'hard'
augroup pencil
  autocmd!
  autocmd FileType md,markdown,mkd call pencil#init()
  autocmd FileType xml,html        call pencil#init()
  autocmd BufNewFile,BufRead /var/tmp/mutt* call pencil#init()
  autocmd FileType text            call pencil#init({'wrap': 'hard'})
augroup END

" Activate Goyo and Pencil with F12
noremap <F12> :Goyo <bar> :TogglePencil <CR>

" Use % to jump to matches
" documentation: https://github.com/chrisbra/matchit/blob/master/doc/matchit.txt
packadd! matchit

ab alise Association for Library and Information Science Education
ab asist Association of Information Science & Technology
ab uk University of Kentucky
ab cci College of Communication and Information
ab sis School of Information Science
