set nocompatible
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent
set number
set ignorecase
set smartcase
set incsearch
set nohlsearch
set hidden
set noerrorbells visualbell t_vb=
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set encoding=utf-8
set nospell
setlocal spelllang=en_us
set spellfile=~/.vim/spellfile.add
set scrolloff=6
set wildmenu
set wildmode=list:longest,full
set showmatch
set magic
set shortmess+=Is
set noequalalways
set splitbelow
set splitright
set nofoldenable
set nojoinspaces
set background=dark
set t_Co=256
set nowrap
set textwidth=0
set wrapmargin=0
hi ColorColumn ctermbg=green
set cursorline
hi CursorLine cterm=NONE ctermbg=NONE ctermfg=white
cabbrev help tab help
let mapleader=","

""" Remappings """

" source ~/.vimrc
nnoremap <silent> <F5> :source ~/.vimrc
" quick wordcount
nnoremap <silent> <F7> g<C-G>
" tab management
nnoremap <leader>tt :tabnew<cr>
nnoremap <leader>tc :tabclose<cr>
nnoremap <leader>tm :tabmove
nnoremap <leader>tn :tabnext<cr>
nnoremap <leader>tp :tabprevious<cr>
" splits
nnoremap <C-t> <C-w><C-r> " rotate splits
nnoremap <C-d> <C-W>w
nnoremap <C-j> <C-W><C-j> " down
nnoremap <C-k> <C-W><C-k> " up
nnoremap <C-l> <C-W><C-l> " right
nnoremap <C-h> <C-W><C-h> " left

""" Plugins """

call plug#begin('~/.vim/plugged')
Plug 'jalvesaq/Nvim-R'
Plug 'gaalcaras/ncm-R'
Plug 'junegunn/goyo.vim'
Plug 'preservim/vim-pencil'
Plug 'preservim/vim-wordy'
Plug 'godlygeek/tabular'
Plug 'Ron89/thesaurus_query.vim'
Plug 'jalvesaq/zotcite'
Plug 'mbbill/undotree'
"Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0'}
call plug#end()

filetype plugin on

" Omnicompletion (e.g., ZotCite)
set omnifunc=syntaxcomplete#Complete
let $ZCitationTemplate = '{author}{year}'

" R integration
let Rnvimpager="vertical"
let R_editor_w=80
let R_objbr_place = "RIGHT"

" For Pencil Plugin
let g:pencil#autoformat = 1             " 0=disable, 1=enable (def)
let g:pencil#wrapModeDefault = 'soft'   " default is 'hard'
set statusline=%<%f\ %h%m%r%w\ \ %{PencilMode()}\ %=\ col\ %c%V\ \ line\ %l\,%L\ %P
set rulerformat=%-12.(%l,%c%V%)%{PencilMode()}\ %P
let g:pencil#mode_indicators = {'hard': '␍', 'auto': 'ª', 'soft': '⤸', 'off': '',}
augroup pencil
  autocmd!
  "autocmd FileType md,markdown,mkd call pencil#init({'nowrap': 'hard'})
  autocmd FileType xml,html        call pencil#init()
  "autocmd BufNewFile,BufRead /var/tmp/mutt* call pencil#init()
  "autocmd FileType text            call pencil#init({'wrap': 'hard'})
augroup END

" Activate UndoTree
nnoremap <F6> :UndotreeToggle<CR>
if has("persistent_undo")
   let target_path = expand('~/.vim/undodir')

    " create the directory and any parent directories
    " if the location does not exist.
    if !isdirectory(target_path)
        call mkdir(target_path, "p", 0700)
    endif

    let &undodir=target_path
    set undofile
endif

" Activate Goyo and Pencil with F12
noremap <F12> :Goyo <bar> :TogglePencil <CR>
" Goyo configurations
let g:goyo_width = 60

" netrw
let g:netrw_liststyle = 3   " tree listing (pree i to switch modes)
let g:netrw_altv = 1        " opens directory vertically and narrow 
let g:netrw_winsize = 30    " controls size of netwr window
