#!/bin/bash

## Written by Sean Burns
## Date: Wed Sep 19 00:02:08 EDT 2018
## Purpose: Batch create user accounts and directories on Linux server

## TO DO: find a more appropriate password generator; fix the for loop; or
# reconfigure pwgen to pass ## ... libpam-cracklib settings

# Assign user list to variable
# Each line in the file has one username, single column, no spaces:
# user1
# user2
# user3
# This file should be generated by the 'check_user_duplicates' script
user_file="users_to_add.txt"

# Add users to specific group
# Assumes group_name exists on system
# One purpose: To allow SSH access for the group (separately)
group_name="name_of_user_group"

# If group does not exist, then exit:
if ! grep -qs "$group_name" /etc/group ; then
  printf "Group %s did not exist. Creating now.\n" "$group_name"
  groupadd "$group_name"
fi

# Create users, one line at a time
while read -r name ; do
  useradd -m -U -s /bin/bash -G "$group_name" "$name"
done<"$user_file"

# Get total count of users. Assign number to variable
# use redirect with 'wc' to just get the count/number
total_users=$(wc -l < "$user_file")

# Create unique temporary passwords for each username
# save to a file called 'userpw'
# remove colons with sed and, if they exist, replace with some random character
# e.g., the letter L
# because chpasswd uses colons as a file separator
for i in $(seq 1 "$total_users") ; do
  pwgen -cns 20 | cut -d " " -f 1 >> userpw
  sed -i 's/:/L/g' userpw
done

# Join usernames to temporary passwords
paste -d ":" "$user_file" userpw > pwuser
chmod 600 pwuser

# Update passwords for the users
chpasswd < pwuser
rm userpw
