#!/bin/bash

# Date: 1/24/2021
# A way to check if I have new email
# Specifically, check to see if the Maildir new/ is greater than 0
# Checks several Maildir directories where I receive new email

checkmail() {

  # define base email directory
  base_dir="$HOME/Mail"

  # assign mailboxes that I want to check for new email to an array
  # make sure there's an ending forward slash
  mailboxes=("$base_dir/INBOX/" "$base_dir/association_lists/"
    "$base_dir/university_lists/" "$base_dir/library_lists/"
    "$base_dir/courses/")

  # loop through each mailbox in the array and check if there's email in
  # the new/ Maildir
  #
  # I commented out the two lines below because I'd rather not have
  # anything echo if there's nothing to report, but they're useful for
  # error checking, and so I'll keep them there.

  for mail in "${mailboxes[@]}"; do
    if [ -s "$mail"new/ ] ; then
      echo "You have mail in $mail."
    fi
  done

}

main() {
  checkmail
}

main
