#!/usr/bin/env bash

# Date: September 12, 2019

# Get a count of all members of the 'faculty/staff' group on the server and
# list them

total_fac=$(grep "faculty" /etc/group | \
  sed -e 's/:/\n/g' | tail -n1 | sed -e 's/,/\n/g' | wc -l)

printf "\n"
printf "There are %s faculty or staff accounts.\n" "${total_fac}"
printf "\n"
printf "They include the following:\n"
grep "faculty" /etc/group | sed -e 's/:/\n/g' | tail -n1 | sed -e 's/,/\n/g'
printf "\n"
