#!/bin/bash

# Date: 1/24/2021
# A way to check if I have new email
# Specifically, check to see if the Maildir new/ is greater than 0
# Checks several Maildir directories where I receive new email

checkmail() {

base_dir="$HOME/Mail"

mdirs=("$base_dir/INBOX/" "$base_dir/association_lists"
  "$base_dir/university_lists/" "$base_dir/library_lists"
  "$base_dir/courses/")

for mail in "${mdirs[@]}"; do
  if [ -s "$mail"new/ ] ; then
    echo "You have mail in $mail."
  else
    echo "No new mail in $mail."
  fi
done

}

main() {
  checkmail
}

main
