#!/usr/bin/env bash

## Written by Sean Burns
## Date: 2018-08-18
## Purpose: Batch remove user accounts on Linux server
## Remove same accounts created with the create_accounts script

# Assign user list to variable
# Each line in user_list_file.csv has one username
userfile="user_list_file.csv"

while read -r i ; do
	userdel -r "$i"
done<"$userfile"
