#!/usr/bin/env python3

# Use as a countdown timer
# Usage: timer [arg]
# where [arg] is a positive number
# Date: 2021-07-16

import os 
import time
import argparse

os.system('clear')

# Function to take a positive, whole number 
def take_input():
    count_start = argparse.ArgumentParser()
    count_start.add_argument("number",
            help = "Enter a whole, positive number.", type=int)
    args = count_start.parse_args()
    return args
    os.system('clear')

# Do the countdown
def timer():
    args = take_input()
    for args.number in reversed(range(abs(args.number))):
        print(args.number)
        time.sleep(1)
        os.system('clear')
    print("Countdown over.")

# Call timer function 
timer()
