#!/usr/bin/env python3

""" User as a countdown timer.

Usage: timer [arg]
where [arg] is a positive number
Date: 2021-07-16
"""

import os
import time
import argparse

os.system("clear")


def take_input():
    """Function to take a positive, whole number

    Args:
        integer

    Example:
        timer_cli 10
    """

    count_start = argparse.ArgumentParser()
    count_start.add_argument("number", help="Enter a whole, positive number.", type=int)
    args = count_start.parse_args()
    return args


def timer():
    """Start the countdown"""
    args = take_input()
    for args.number in reversed(range(abs(args.number))):
        print(args.number)
        time.sleep(1)
        os.system("clear")
    print("Countdown over.")


# Call timer function
if __name__ == "__main__":
    timer()
