#!/usr/bin/env bash

# Description: Get counts of Linux users in particular group
# Date: Fri Sep 14 09:34:02 EDT 2018

# use 'getent' to list all groups and members
# use 'grep' to locate group of interest
# use 'cut' to remove non-membership info (i.e.,the first four fields)
# use 'tr' to replace commans with newlines (each member on their own line)
# use 'wc' to count the number of members

name_group="$1"

getent group | \
  grep "^${name_group}" | \
  cut -d: -f4 | \
  tr , '\n' | \
  echo "There are $(wc -l) accounts in ${name_group}."
