#!/usr/bin/env python3

""" A little script that follows the Wim Hof Breathing method.

Usage: ./wimhof -h [short_breaths] [long_breath_hold] [total_rounds]
Pretty much follows the following video:
https://www.youtube.com/watch?v=tybOi4hjZFQ
Date: 2021-07-19
To do: Make pretty
To do: Press a key to end the long_breath_hold early
"""

def play_intro():

    """ Introduce and start the breathing exercise."""

    os.system('clear')
    print("Press Ctrl-c at any time to quit")
    print("For *nix machines, press Ctrl-z to pause and fg to unpause")
    time.sleep(1.5)
    print("'All right, guys, welcome.'")
    time.sleep(1.5)
    print("'This is a guided breathing session.'")
    time.sleep(1.5)
    print("'Relax to the deepest.'")
    time.sleep(1.5)
    print("'Whatever it takes, relax.'")
    time.sleep(1.5)
    print("'Are you ready?'")
    time.sleep(1.5)
    print("'Here we go.' --Wim Hof")
    time.sleep(1.5)
    os.system('clear')

def take_input():
    """ State the breathing exercise parameters.

    Args:
        Number of short breaths.
        Duration of long breaths.
        Total number of rounds.

    Example:
        wimhof 30 190 3
    """

    parser = argparse.ArgumentParser(description = "Practice the Wim Hof Breathing Method")
    parser.add_argument("short_breaths",
            help = "Number of short breaths (standard 30).",
            type = int)
    parser.add_argument("long_breaths",
            help = "Duration of long breath hold (standard 190).",
            type = int)
    parser.add_argument("total_rounds",
            help = "Total number of rounds (standard 3).",
            type = int)
    args = parser.parse_args()
    return args

def breath():
    """ Function to define short breaths """

    args = take_input()
    for i,j in zip(range(1,args.short_breaths + 1), range(1,args.short_breaths + 1)):
        print("Breath in", i)
        time.sleep(1.7)
        print("Breath out", j)
        time.sleep(1.7)

def breathout_hold():
    """ Function to define the length of the breath hold."""

    args = take_input()
    print(f"Hold breath for {args.long_breaths} seconds")
    for k in reversed(range(1,args.long_breaths + 1)):
        print(k, "seconds left")
        time.sleep(1)

def breathin_hold():
    """ Function to define the length of the breath hold."""

    print("Breath in and hold for 15 seconds")
    for hold_time in reversed(range(1,16)):
        print(hold_time, "seconds left")
        time.sleep(1)

def play_closing():
    """ Wrap up and end the breathing excercise."""

    print("'Let it go.'")
    time.sleep(1.5)
    print("'Let your breathing return to normal as you finish up the round.'")
    time.sleep(1.5)
    print("'Move your body bit by bit, starting with your fingers and your toes.'")
    time.sleep(1.5)
    print("'Let your breathing normalize.' --Wim Hof")
    sys.exit()

def rounds():
    """ Define the order of the rounds."""

    while True:
        try:
            args = take_input()
            play_intro()
            for round_no in range(1,args.total_rounds + 1):
                print("ROUND NUMBER ", round_no)
                breath()
                breathout_hold()
                breathin_hold()
                os.system('clear')
            play_closing()
        except KeyboardInterrupt:
            sys.exit("You pressed Ctrl-c to stop early.")

# Run the script
if __name__ == '__main__':
    import os
    import time
    import argparse
    import sys
    rounds()
