#!/usr/bin/env bash

# Office hour script in Bash; also available in Python!

officeday=$(date +%a)
day1="Tue"
day2="Wed"
email="myemail@uky.edu"

/usr/bin/clear
printf "Christopher Sean Burns, PhD\n"
printf "Associate Professor\n"
printf "%s\n" "$email"
printf "859-555-0000\n"
printf "\nSpring 2020\n"
 
if [[ "$officeday" = "$day1" ]] ; then
  printf "\nSince today is %s, my office hours are 1:00-3:00PM.\n" "$day1"
elif [[ "$officeday" = "$day2" ]] ; then
  printf "\nSince today is %s, my office hours are 1:00-3:00PM.\n" "$day2"
else
  printf "\nSince today is neither %s nor %s,\n" "$day1" "$day2"
  printf "please knock on door or email me at\n"
  printf "%s\n" "$email"
  printf "to schedule an appointment.\n"
fi
