#!/bin/bash

## Written by Sean Burns
## Date: 2018-08-28
## Purpose: Batch create user accounts and directories on Linux server
## I removed forcing password change from previous version (v-01)

## TO DO: test if users exists; then skip those users
## TO DO: test if group exists; then exit if it doesn't
## TO DO: create public_html directory for users since userdir module is added
## TO DO: find better password generator or reconfigure pwgen to pass
## ... libpam-cracklib settings

# Assign user list to variable
# Each line in the file has one username, single column, no spaces
userfile="user_list_file.csv"

# Add users to specific group
# Assumes group_name exists on system
# One purpose: To allow SSH access for the group (separately)
group_name="name_of_user_group"

# Create users, one line at a time
while read i ; do
  useradd -m -U -s /bin/bash -G "$group_name" "$i"
done<"$userfile"

# Get total count of users. Assign number to variable
# use redirect with 'wc' to just get the count/number
totalusers=$(wc -l < "$userfile")

# Create unique temporary passwords for each username
# save to a file called 'userpw'
# remove colons with sed and, if they exist, replace with some random character
# e.g., the letter L
# because chpasswd uses colons as a file separator
for i in $(seq 1 "$totalusers") ; do
  pwgen -cny 12 | cut -d " " -f 1 >> userpw
  sed -i 's/:/L/g' userpw
done

# Join usernames to temporary passwords
paste -d ":" "$userfile" userpw > pwuser

# Update passwords for the users
chpasswd < pwuser
